include: package:flutter_lints/flutter.yaml

formatter:
      trailing_commas: preserve
analyzer:
      errors:
        constant_identifier_names: ignore
        non_constant_identifier_names: ignore
